#!/usr/bin/env bash

if [ -z "$PORT" ]; then
    export PORT=8080
    echo "PORT env var required; defaulting to $PORT"
fi

# Change to pop directory before running
cd "$(dirname "${BASH_SOURCE}")" && echo "Working from ${PWD}"

echo "Installing vendored dependencies..."
go install ./...

# Timed start on separate thread
echo "Opening in default browser..." && sleep 1 && open http://localhost:${PORT} &

echo "Starting server on port ${PORT}"
go build && ./protestpulse
