#!/usr/bin/env bash

if [ -z "$PORT" ]; then
    export PORT=8080
    echo "PORT env var required; defaulting to $PORT"
fi

# Change to directory before running
cd "$(dirname "${BASH_SOURCE}")" && echo "Working from ${PWD}"

echo "Installing vendored dependencies..."
go install ./...

# Start database and run schema
pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start
psql -h localhost -d postgres -f sql/schema.sql
psql -U ppmaster -h localhost -d ppdb -f sql/test_data.sql

# Timed start on separate thread
echo "Opening in default browser..." && sleep 1 && open http://localhost:${PORT} &

echo "Starting server on port ${PORT}"
go build && ./protestpulse
